config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('equipment/', include('equipment.urls')),#equipmentのurls.pyへ接続
    path('', include('users.urls')),              #usersアプリのurls.pyへ接続
    path('order_history/', include('order.urls')),  # orderアプリのurls.pyへ接続
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)#画像ファイルをどこに格納するか→場所はsettings.pyで指定

equipment/urls.py
from django.urls import path
from . import views
from .views import equipment_list,EquipCreateView,EquipDetailView,EquipUpdateView,EquipDeleteView,CommentDeleteView

app_name = 'equipment'#逆引きするときにどういう名前で呼び出すか…たとえば、equipment:list等の名前で呼び出せるようになる app_name:name(urlpatternsの中のname)

urlpatterns = [
    path('', equipment_list, name='list'),#equipment/(空のパス)/にアクセスが来たら、views.pyで定義しているequipment_listを参照する
    path('loan/<int:pk>/', views.loan_equipment, name='loan_equipment'),
    path('return/<int:pk>/', views.return_equipment, name='return_equipment'),
    path('add/', EquipCreateView.as_view(), name='add'),#equipment/add/にアクセスが来たら、views.pyで定義しているEquipCreateViewを参照する
    path('<int:pk>', EquipDetailView.as_view(), name='detail'),#equipment/(備品id)/にアクセスが来たら、views.pyで定義しているEquipCreateViewを参照する
    path('<int:pk>/edit/', EquipUpdateView.as_view(), name='edit'),#equipment/(備品id)/edit/にアクセスが来たら、views.pyで定義しているEquipUpdateViewを参照する
    path('<int:pk>/delete/', EquipDeleteView.as_view(), name='delete'),#equipment/(備品id)/delete/にアクセスが来たら、views.pyで定義しているEquipDeleteViewを参照する
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment-delete'),#コメント削除用機能
]

order/urls.py
from django.urls import path
from .views import OrderListView

app_name = 'order'
urlpatterns = [
    path('', OrderListView.as_view(), name='history'),
]

equipment/models.py
from django.db import models
from django.conf import settings

#備品管理に関係するデータベースを定義
class Equipment(models.Model):
  class Meta:
    db_table = 'equip'
    #テーブルの名前を'equip'にする
    #(ここで定義しない場合は、アプリケーション名 と モデル名 をアンダースコアでつないだものがテーブル名になる： 'equipment_equipment')

  equip_name = models.CharField(max_length=50,null=False)
  category = models.CharField(max_length=50,null=False)
  place = models.CharField(max_length=50,null=False)
  condition  = models.CharField(max_length=50,null=False)
  stock = models.PositiveIntegerField(null=False, default=1)
  text = models.TextField(null=False)
  web_site = models.URLField(blank=True) #URL入力箇所を追加
  image = models.ImageField(upload_to='images/', blank=False, null=False)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,null=True)
      # 貸出状況を選択制にして追加
  LOAN_STATUS_CHOICES = [
        ('貸出可', '貸出可'),
        ('貸出中', '貸出中'),
        ('貸出不可', '貸出不可'),
        ('その他', 'その他（説明欄に詳細）'),    ]
  loan_status = models.CharField(choices=LOAN_STATUS_CHOICES,null=True,blank=True,max_length=50)


#在庫数変更履歴に関係するデータベースを定義
class StockChange(models.Model):
    class Meta:
      db_table = 'stockchange'
       #テーブルの名前を'stockchange'にする

    equip = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    changed_date = models.DateTimeField(auto_now_add=True)
    previous_stock = models.PositiveIntegerField()
    new_stock = models.PositiveIntegerField()

#コメント機能を定義
class Comment(models.Model):
    class Meta:
      db_table = 'comment'

    equip = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField(null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True) #不要かもしれないけど一応追加しておく

equipment/forms.py
from .models import Equipment,Comment
from django import forms

class EquipForm(forms.ModelForm):
    class Meta:
      model = Equipment
      fields = ['equip_name','category', 'condition','loan_status','place','text','web_site','image','stock']
      labels = {
         'equip_name':'名前',
         'category': 'カテゴリ',
         'condition': '状態',
         'loan_status': '貸出状況',
         'place': '設置場所',
         'text': '説明',
         'web_site': '参考URL',
         'image': '画像',
         'stock': '在庫数',
      }

class StockUpdateForm(forms.ModelForm):
    class Meta:
        model = Equipment
        fields = ['stock']
        labels = {
         'stock': '在庫数',
      }

class CommentForm(forms.ModelForm):
    class Meta:
      model = Comment
      fields = ['text']
      labels = {
         'text': 'コメント',
      }
      widgets = {
         'text': forms.Textarea(attrs={'placeholder': 'コメントを入力...'}),
        }

equipment/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.urls import reverse_lazy
from .models import Equipment,StockChange,Comment
from django.contrib.auth.mixins import LoginRequiredMixin #ログインしてないと見れないようにするやつ
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView,DetailView,UpdateView,DeleteView,TemplateView
from .forms import EquipForm,StockUpdateForm,CommentForm
from order.forms import OrderForm
from order.models import Order
from django.http import HttpResponseForbidden,HttpResponseRedirect,HttpResponse,JsonResponse #アクセスを禁止するためのヤツ
from users.models import FavoriteEquip
from datetime import datetime, timedelta
import calendar
from django.utils import timezone
from django.template.loader import render_to_string

#書籍管理一覧
@login_required#ログインしていないと見れないようにするデコレータを追加
def equipment_list(request):
    equipments = Equipment.objects.all().order_by('-updated_at')
    return render(request, 'equipment/list.html', {'equipments': equipments})#equipment_list.htmlをlist.htmlに修正 #テンプレート上で、データをequipmentsという名前で呼び出す

# 貸出処理
def loan_equipment(request, pk):
    equipment = get_object_or_404(Equipment, pk=pk)
    equipment.loan_status = '貸出中'
    equipment.save()
    return redirect('equipment:list')

# 返却処理
def return_equipment(request, pk):
    equipment = get_object_or_404(Equipment, pk=pk)
    equipment.loan_status = '貸出可'
    equipment.save()
    return redirect('equipment:list')


#書籍追加ページ
class EquipCreateView(LoginRequiredMixin, CreateView):#CREATE用のビューを使う＆ログインしてないと見れないようにする
    template_name = 'equipment/add.html'# テンプレートはadd.htmlを使用
    model = Equipment # モデル(データベース)は、models.pyで定義しているEquipmentモデルを使用する
    form_class = EquipForm  # フォームは、forms.pyで定義しているEquipFormを使用する
    success_url = reverse_lazy('equipment:list')#登録できたら備品一覧画面に戻る

    def form_valid(self, form):#フォームに入力された内容が形式上正しいかをチェックする
        form.instance.user = self.request.user#チェックできたら登録したユーザーが誰かという情報を取得する、
        return super().form_valid(form)#登録を完了させる

#書籍詳細表示ページ
class EquipDetailView(LoginRequiredMixin, DetailView):
    model = Equipment
    template_name = 'equipment/detail.html'
    context_object_name = 'equip' #ここの名前でテンプレート上で呼び出す

    def get_context_data(self, **kwargs):#画像がエラーになった時用の回避策
        context = super().get_context_data(**kwargs)
        equip = context['equip']
        user = self.request.user
        now = timezone.now().date()  # 現在の日付を取得

        context['stock_update_form'] = StockUpdateForm(instance=equip) #在庫数更新のフォームが使えるようになる、instance=equipは、今ビューで処理しているequipのデータを初期設定として入れておく、の意味
        context['stock_changes'] = StockChange.objects.filter(equip=equip).order_by('-changed_date')[:5]#StockChangeモデルのデータが使えるようになる
        context['order_form'] = OrderForm() #貸出数更新フォームが使えるようになる
        context['orders'] = Order.objects.filter(equip=equip).order_by('-order_date')[:5]#Orderモデルのデータが使えるようになる
        context['is_favorite'] = FavoriteEquip.objects.filter(user=user, equip=equip).exists()# お気に入り情報を追加
        context['favorite_count'] = FavoriteEquip.objects.filter(equip=equip).count()#お気に入り登録人数をカウント
        context['comments'] = Comment.objects.filter(equip=equip).order_by('created_at')
        context['comment_form'] = CommentForm() #コメントフォームが使えるようになる

        # 貸出予定リスト用！承認済みで、貸出希望日または返却予定日が未来のものを取得し、5件に絞る
        context['future_orders'] = (
            Order.objects.filter(
                equip=equip,
                approval_status='承認済み',
                loan_date__gte=now  # 貸出希望日が現在以降
            )
            .union(
                Order.objects.filter(
                    equip=equip,
                    approval_status='承認済み',
                    return_date__gte=now  # 返却予定日が現在以降
                )
            )
            .order_by('loan_date')[:5]  # 貸出希望日でソートして5件に絞る
        )



        # カレンダー部分のコンテキストをヘルパーメソッドで取得
        calendar_context = get_calendar_context(
            request=self.request,
            year=self.request.GET.get('year'),
            month=self.request.GET.get('month'),
            equip=self.object
        )

        # カレンダーのコンテキストをマージする
        context.update(calendar_context)

        return context

    def render_to_response(self, context, **response_kwargs):
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            # AJAXリクエストの場合、カレンダーの部分だけ返す
            html = render_to_string('equipment/calendar_partial.html', context, request=self.request)
            return HttpResponse(html)
        else:
            # 通常のリクエストの場合、全体を返す
            return super().render_to_response(context, **response_kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        previous_stock = self.object.stock# フォームを保存する前に、更新前の在庫数を取得しておく

    ### 在庫数更新フォームの処理
        stock_update_form = StockUpdateForm(request.POST, instance=self.object)
        if stock_update_form.is_valid():
        # フォームを保存する
            updated_equip = stock_update_form.save()

        # StockChangeテーブルに変更履歴を保存
            StockChange.objects.create(
            equip=self.object,
            user=request.user,
            previous_stock=previous_stock,
            new_stock=updated_equip.stock,
        )

    #### 貸出フォームの処理
        order_form = OrderForm(request.POST)
        if order_form.is_valid():
            order = order_form.save(commit=False)
            order.equip = self.object
            order.user = request.user
            order.save()
            return redirect(self.get_success_url() + '?loan_success=true')

        # 承認ボタンが押されたかを確認
        order_id = request.POST.get('approve_order')
        if order_id:
            order = get_object_or_404(Order, pk=order_id)
            order.approve(request.user)  # Orderモデルにある'approve'メソッドを使って承認処理を実行
            return HttpResponseRedirect(request.path_info)  # リダイレクトして、ページ更新時の再送信を防ぐ
 
        # 否決ボタンが押されたかを確認
        reject_order_id = request.POST.get('reject_order')
        if reject_order_id:
            order = get_object_or_404(Order, pk=reject_order_id)
            order.reject(request.user)  # Orderモデルに'reject'メソッドを定義し、否決処理を実行
            return HttpResponseRedirect(request.path_info)  # リダイレクトして、ページ更新時の再送信を防ぐ

    ### お気に入り機能
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        # お気に入り登録・解除の処理
            equip_id = request.POST.get('equip_id')
            equipment = get_object_or_404(Equipment, id=equip_id)
            user = request.user

            favorite, created = FavoriteEquip.objects.get_or_create(user=user, equip=equipment)
            if not created:
                favorite.delete()
                favorite_count = FavoriteEquip.objects.filter(equip=equipment).count()
                return JsonResponse({'status': 'removed', 'favorite_count': favorite_count})
            else:
                favorite_count = FavoriteEquip.objects.filter(equip=equipment).count()
                return JsonResponse({'status': 'added', 'favorite_count': favorite_count})

        ### コメント機能
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.equip = self.object
            comment.user = request.user
            comment.save()

            return redirect(self.get_success_url() + '?comment_success=true')

        return self.render_to_response(self.get_context_data(
            stock_update_form=stock_update_form,
            order_form=order_form
        ))
    def get_success_url(self):
        return reverse_lazy('equipment:detail', kwargs={'pk': self.object.pk})


#書籍編集ページ
class EquipUpdateView(LoginRequiredMixin, UpdateView):
    model = Equipment
    form_class = EquipForm
    template_name = 'equipment/edit.html'
    
    def get_success_url(self):
         return reverse_lazy('equipment:detail', kwargs={'pk': self.object.pk}) + '?success=true'
    #管理者以外に書籍編集ページへのアクセスを許可しない
    def dispatch(self, request, *args, **kwargs):#管理者以外に書籍編集ページへのアクセスを許可しない
    # ログインユーザーのis_adminがTrueかどうかをチェック
        if not request.user.is_admin:
            return HttpResponseForbidden("編集権限がありません。")
        return super().dispatch(request, *args, **kwargs)


#書籍削除
class EquipDeleteView(LoginRequiredMixin, DeleteView): #アクセスがきたら削除するだけなのでテンプレートの設定はなし
    model = Equipment
    success_url = reverse_lazy('equipment:list')

    def dispatch(self, request, *args, **kwargs):#管理者以外に削除機能へのアクセスを許可しない
    # ログインユーザーのis_adminがTrueかどうかをチェック
        if not request.user.is_admin:
            return HttpResponseForbidden("削除権限がありません。")
        return super().dispatch(request, *args, **kwargs)


#コメント削除機能
class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment

    def get_success_url(self):
        # コメントが関連付けられている備品の詳細ページにリダイレクトする
        return reverse_lazy('equipment:detail', kwargs={'pk': self.object.equip.pk})

    def dispatch(self, request, *args, **kwargs):
        comment = self.get_object()

        # コメント投稿者または管理者のみが削除可能
        if request.user != comment.user and not request.user.is_admin:
            return HttpResponseForbidden("このコメントを削除する権限がありません。")
        
        return super().dispatch(request, *args, **kwargs)



#カレンダー機能：ヘルパーメソッド
def get_calendar_context(request, year=None, month=None, equip=None):
   # URLから年と月のパラメータを取得し、明示的にint型に変換
   year = int(request.GET.get('year', datetime.now().year)) if year is None else int(year)
   month = int(request.GET.get('month', datetime.now().month)) if month is None else int(month)
   # 月の最初の日が何曜日か（0=月曜日, 6=日曜日）とその月の日数を取得
   first_weekday, days_in_month = calendar.monthrange(year, month)
   # 月曜日始まりから日曜日始まりに変換
   if first_weekday == 6:  # 日曜日の場合
       first_weekday = 0
   else:
       first_weekday += 1
   days_in_month_range = range(1, days_in_month + 1)
   # 空のセルの数（first_weekday の値分）
   empty_days = range(first_weekday)
   # 貸出予定を取得（フィルタ条件はアプリに応じて変更）
   loaned_days = set()
   future_orders = Order.objects.filter(
       equip=equip,
       loan_date__year__lte=year,

templates/equipment/add.html
{% extends "base.html" %}
{% load static %}
{% block title %}書籍登録{% endblock title %}
{% block content %}

    <!-- 書籍一覧へ戻るボタン（相対的な位置に配置）-->
    <div class="button-container">
        <a href="{% url 'equipment:list' %}" class="return-button">書籍一覧へ戻る</a>
    </div>
    <div class="title">
        <h2>書籍登録</h2>
        <p><span class="field-error">※</span>は入力必須項目です</p>
    </div>
    <div class="content">
        <form method="post" action="{% url 'equipment:add' %}" enctype="multipart/form-data">
            {% csrf_token %}
            {% if form.errors %}
            <div class="field-error">
                <p>入力にエラーがあります。もう一度ご確認ください。</p>
                {{ form.non_field_errors }}
            </div>
            {% endif %}
            
            <div class="field">
                <label for="{{ form.equip_name.id_for_label }}">名前<span class="field-error">※</span></label>
                {{ form.equip_name }}
            </div>
            <div class="field">
                <label for="{{ form.category.id_for_label }}">カテゴリ<span class="field-error">※</span></label>
                {{ form.category }}
            </div>
            <div class="field">
                <label for="{{ form.condition.id_for_label }}">状態<span class="field-error">※</span></label>
                {{ form.condition }}
            </div>
            <div class="field">
                <label for="{{ form.loan_status.id_for_label }}">貸出状況</label>
                {{ form.loan_status }}
            </div>
            <div class="field">
                <label for="{{ form.place.id_for_label }}">設置場所<span class="field-error">※</span></label>
                {{ form.place }}
            </div>
            <div class="field">
                <label for="{{ form.text.id_for_label }}">説明<span class="field-error">※</span></label>
                {{ form.text }}
            </div>
            <div class="field">
                <label for="{{ form.web_site.id_for_label }}">参考URL</label><span class="field-error"><small>（Amazon等書籍の説明が記載されているURLを入力）</small></span>
                {{ form.web_site }}
            </div>
            <div class="field">
                <label for="{{ form.image.id_for_label }}">画像<span class="field-error">※</span></label>
                {{ form.image }}
            </div>
            <div class="field">
                <label for="{{ form.stock.id_for_label }}">在庫数<span class="field-error">※</span></label>
                {{ form.stock }}
                <span class="field-error"><small>・原則在庫数は1としてください。<br>・それ以外の場合は詳細を「説明」欄に記載してください。</small></span>
            </div>
            <div class="button-container">
                <input type="submit" value="登録" class="button">
            </div>
        </form>
    </div>
        <!-- 書籍一覧へ戻るボタン（相対的な位置に配置）-->
        <div class="button-container">
            <a href="{% url 'equipment:list' %}" class="return-button">書籍一覧へ戻る</a>
        </div>
    
<!-- 閉じるボタン -->
<div class="close-button-container">
    <span class="close-text">閉じる</span> <!-- 閉じるの文字を追加 -->
    <span class="close-button" onclick="closeModal()">&times;</span> <!-- 閉じる×ボタン -->
</div>

<!-- モーダル内のみに適用するスタイル -->
<style>
    /* このページの背景画像を非表示にする */
    body {
        background-image: none;
    }
    
    /* モーダル内でヘッダーとフッターを非表示にする */
    .modal header, .modal footer {
        display: none;
    }
    /* モーダル内で .title-logo を無効にする */
.modal .title-logo {
    display: none;
}
    /* 書籍一覧ボタン */
    .return-button {
        position: absolute;
        top: 20px;
        left: 20px;
        padding: 10px 20px;
        text-decoration: none;
        border-radius: 5px;
        z-index: 1001;
    }
    .close-button-container {
        top: 20px;
        right: 20px;
        text-align: center;
    }
    .close-content {
        display: flex;
        flex-direction: column; /* 縦方向に並べる */
        align-items: center; /* 中央揃え */
    }
    .close-text {
        font-size: 12px;
        color: #333;
        margin-bottom: 5px; /* 「×」と「閉じる」の間のスペース */
    }
    .close-button {
        font-size: 24px;
        color: #333;
        cursor: pointer;
    }
    .close-button:hover {
        color: #f00; /* ホバー時に赤色に変更 */
    }
</style>
{% endblock content %}

templates/equipment/calendar_partial.html
<div class="calendar-navigation">
  <a href="?year={{ prev_month_year }}&month={{ prev_month }}">前月</a>
  <span>{{ current_year }}年{{ current_month }}月の貸出予定</span>
  <a href="?year={{ next_month_year }}&month={{ next_month }}">次月</a>
</div>

<div class="calendar">
  <!-- 曜日のヘッダー -->
  <div class="dayofweek sunday">日</div><div class="dayofweek">月</div><div class="dayofweek">火</div><div class="dayofweek">水</div><div class="dayofweek">木</div><div class="dayofweek">金</div><div class="dayofweek saturday">土</div>

  <!-- 最初の日の前に空のセルを挿入して曜日を調整 -->
  {% for _ in empty_days %}
    <div class="empty"></div>
  {% endfor %}

  <!-- カレンダーの日付を表示 -->
  {% for day in days_in_month %}
    <div class="{% if day in loaned_days %}loaned{% endif %}">{{ day }}</div>
  {% endfor %}
</div>

<center><span class="status-approved"><font size="6">■</font></big></span>＝貸出予定あり</center>

templates/equipment/edit.html
{% extends "base.html" %}
{% load static %}
{% block title %}書籍編集{% endblock title %}
{% block content %}
{% comment %} このページは、<add.html>とまったく同じ内容で大丈夫です！ {% endcomment %}

    <div class="button-container">
        <a href="javascript:history.back()" class="return-button">書籍詳細へ戻る</a>
    </div>

<div class="title">
    <h2>書籍編集</h2>
</div>

<div class="content">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if form.errors %}
        <div class="field-error">
            <p>入力にエラーがあります。もう一度ご確認ください。</p>
            {{ form.non_field_errors }}
        </div>
        {% endif %}
        
        <div class="field">
            <label for="{{ form.equip_name.id_for_label }}">名前</label>
            {{ form.equip_name }}
        </div>
        <div class="field">
            <label for="{{ form.category.id_for_label }}">カテゴリ</label>
            {{ form.category }}
        </div>
        <div class="field">
            <label for="{{ form.condition.id_for_label }}">状態</label>
            {{ form.condition }}
        </div>
        <div class="field">
            <label for="{{ form.loan_status.id_for_label }}">貸出状況</label>
            {{ form.loan_status }}
        </div>
        <div class="field">
            <label for="{{ form.place.id_for_label }}">設置場所</label>
            {{ form.place }}
        </div>
        <div class="field">
            <label for="{{ form.text.id_for_label }}">説明</label>
            {{ form.text }}
        </div>
        <div class="field">
            <label for="{{ form.web_site.id_for_label }}">参考URL</label><span class="field-error"><small>（Amazon等書籍の説明が記載されているURLを入力）</small></span>
            {{ form.web_site }}
        </div>
        <div class="field">
            <label for="{{ form.image.id_for_label }}">画像</label>
            {{ form.image }}
        </div>
        <div class="field">
            <label for="{{ form.stock.id_for_label }}">在庫数<span class="field-error">※</span></label>
            {{ form.stock }}
            <span class="field-error"><small>※原則在庫数は1としてください。<br>　 それ以外の場合は詳細を「説明」欄に記載してください。</small></span>
        </div>
        <div class="button-container">
            <input type="submit" value="登録" class="button">
        </div>
    </form>
</div>
{% endblock content %}