config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('equipment/', include('equipment.urls')),#equipmentのurls.pyへ接続
    path('', include('users.urls')),              #usersアプリのurls.pyへ接続
    path('order_history/', include('order.urls')),  # orderアプリのurls.pyへ接続
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)#画像ファイルをどこに格納するか→場所はsettings.pyで指定

order/urls.py
from django.urls import path
from .views import OrderListView

app_name = 'order'
urlpatterns = [
    path('', OrderListView.as_view(), name='history'),
]

users/urls.py
from django.urls import path
from .views import IndexView, SignUpView, CustomUserListView, UserUpdateView, MenuView, MyPageView,ForgetPasswordView,FavoriteListView
from django.contrib.auth.views import LoginView,LogoutView

app_name = "users"
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('users/', CustomUserListView.as_view(), name='users'),#ユーザー一覧
    path('users/<int:pk>/edit/', UserUpdateView.as_view(), name='edit'),#ユーザーを編集
    path('register/', SignUpView.as_view(), name='register'),#新規登録
    path('login/', LoginView.as_view(template_name='users/sign_in.html'), name='login'),#ログイン機能
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),#ログアウト機能
    path('menu/', MenuView.as_view(), name='menu'),#ログアウト機能
    path('mypage/', MyPageView.as_view(), name='mypage'),  # マイページへのパス
    path('forgetpw/', ForgetPasswordView.as_view(), name='forgetpw'),  # マイページへのパス
    path('favorite/', FavoriteListView.as_view(), name='favorite'),  # お気に入りへのパス
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock title %}</title><!--ページのタイトルは、各ページで設定する-->
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />

</head>
<body>
  <header>
    <div class="header-top">
      {% if user.is_authenticated %} <!--ログインしているときの表示-->
      <a href="{% url 'users:menu' %}" style="text-decoration: none; color: #48A63F;">
        <h2>書籍貸出管理 -Webシステム</h2>
      </a>
      <a class="user-username" href="{% url 'users:mypage' %}"> {{ user.username }} さん
          <!--ユーザー名を押下すると名マイページに飛ぶ※URL部分にに作成した新URLを追加-->
        {% if user.is_admin %}
          (管理者)  <!--ログインユーザーが管理者のときだけ、名前のうしろに(管理者)と表示-->
        {% endif %}
      </a>
      最終ログイン:{{ user.last_login|date:"Y/m/d H:i" }}
      {% else %}
      <a href="{% url 'users:index' %}" style="text-decoration: none; color: #48A63F;">
        <h2>書籍貸出管理 -Webシステム</h2>
      </a>

      {% endif %}
    </div>
      <div class="header-content">
          <div class="left">
              <ul>
                {% if user.is_authenticated %} <!--ログインしているときの表示-->
                <li><a href="{% url 'users:menu' %}">
                  <span class="material-symbols-outlined">other_houses</span>
                HOME</a></li>
                <li><a href="{% url 'equipment:list' %}">
                  <span class="material-symbols-outlined">
                    import_contacts
                    </span>
                  書籍一覧</a></li>
                <li><a href="{% url 'order:history' %}">
                  <span class="material-symbols-outlined">
                    description
                    </span>
                  申請一覧
                    {% if user.is_admin %}
                      {% if pending_orders_count > 0 %}
                        <span class="badge">
                        {% if pending_orders_count > 10 %}
                          10+
                        {% else %}
                          {{ pending_orders_count }}
                        {% endif %}
                        </span>
                      {% endif %}
                      </a></li>
                    {% endif %}
                  <li><a href="{% url 'users:favorite' %}">
                    <span class="material-symbols-outlined">
                      favorite
                      </span>
                      お気に入り一覧
                    </a></li>
                  {% else %}<!--ログインしてないときの表示-->
                {% comment %} <li><a href="{% url 'users:index' %}">ホーム</a></li> {% endcomment %}
                {% endif %}
              </ul>
          </div>
          <div class="right">
              <ul>
                {% if user.is_authenticated %} <!--ログインしているときの表示-->

                  {% if user.is_admin %}<!--ログインユーザーが管理者のときだけ、ユーザー一覧を表示-->

                  <li><a href="{% url 'users:users' %}">
                    <span class="material-symbols-outlined">
                      group
                      </span>
                    ユーザー一覧</a></li>
                  {% endif %}

                <li><a href="{% url 'users:logout' %}">
                  <span class="material-symbols-outlined">
                    logout
                    </span>ログアウト</a></li>
                {% else %}<!--ログインしてないときの表示-->
                {% comment %} <li><a href="{% url 'users:login' %}">ログイン</a></li>
                <li><a href="{% url 'users:register' %}">登録</a></li> {% endcomment %}
                {% endif %}
              </ul>
          </div>
      </div>
  </header>

<!-- トップページのメイン -->
  <div class="title-logo">
  </div>
  <div class="main">
    {% block content %}{% endblock content %}<!--各ページで設定したコンテンツを表示させる-->
  </div>

<!-- フッター -->
  <footer>
    <div class="footer">
      <p>2024 team c</p>
    </div>
  </footer>
  
</body>
</html>