config/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('equipment/', include('equipment.urls')),#equipmentのurls.pyへ接続
    path('', include('users.urls')),              #usersアプリのurls.pyへ接続
    path('order_history/', include('order.urls')),  # orderアプリのurls.pyへ接続
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)#画像ファイルをどこに格納するか→場所はsettings.pyで指定

equipment/urls.py
from django.urls import path
from . import views
from .views import equipment_list,EquipCreateView,EquipDetailView,EquipUpdateView,EquipDeleteView,CommentDeleteView

app_name = 'equipment'#逆引きするときにどういう名前で呼び出すか…たとえば、equipment:list等の名前で呼び出せるようになる app_name:name(urlpatternsの中のname)

urlpatterns = [
    path('', equipment_list, name='list'),#equipment/(空のパス)/にアクセスが来たら、views.pyで定義しているequipment_listを参照する
    path('loan/<int:pk>/', views.loan_equipment, name='loan_equipment'),
    path('return/<int:pk>/', views.return_equipment, name='return_equipment'),
    path('add/', EquipCreateView.as_view(), name='add'),#equipment/add/にアクセスが来たら、views.pyで定義しているEquipCreateViewを参照する
    path('<int:pk>', EquipDetailView.as_view(), name='detail'),#equipment/(備品id)/にアクセスが来たら、views.pyで定義しているEquipCreateViewを参照する
    path('<int:pk>/edit/', EquipUpdateView.as_view(), name='edit'),#equipment/(備品id)/edit/にアクセスが来たら、views.pyで定義しているEquipUpdateViewを参照する
    path('<int:pk>/delete/', EquipDeleteView.as_view(), name='delete'),#equipment/(備品id)/delete/にアクセスが来たら、views.pyで定義しているEquipDeleteViewを参照する
    path('comment/<int:pk>/delete/', CommentDeleteView.as_view(), name='comment-delete'),#コメント削除用機能
]

order/urls.py
from django.urls import path
from .views import OrderListView

app_name = 'order'
urlpatterns = [
    path('', OrderListView.as_view(), name='history'),
]

users/urls.py
from django.urls import path
from .views import IndexView, SignUpView, CustomUserListView, UserUpdateView, MenuView, MyPageView,ForgetPasswordView,FavoriteListView
from django.contrib.auth.views import LoginView,LogoutView

app_name = "users"
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('users/', CustomUserListView.as_view(), name='users'),#ユーザー一覧
    path('users/<int:pk>/edit/', UserUpdateView.as_view(), name='edit'),#ユーザーを編集
    path('register/', SignUpView.as_view(), name='register'),#新規登録
    path('login/', LoginView.as_view(template_name='users/sign_in.html'), name='login'),#ログイン機能
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),#ログアウト機能
    path('menu/', MenuView.as_view(), name='menu'),#ログアウト機能
    path('mypage/', MyPageView.as_view(), name='mypage'),  # マイページへのパス
    path('forgetpw/', ForgetPasswordView.as_view(), name='forgetpw'),  # マイページへのパス
    path('favorite/', FavoriteListView.as_view(), name='favorite'),  # お気に入りへのパス
]

order/models.py
from django.db import models
from django.conf import settings
from equipment.models import Equipment
from django.utils import timezone

class Order(models.Model):
  class Meta:
    db_table = 'order'#テーブルの名前をorderにする

  equip = models.ForeignKey(Equipment, on_delete=models.CASCADE)
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='orders')
  quantity = models.PositiveIntegerField()
  order_date = models.DateTimeField(auto_now_add=True)
  loan_date = models.DateField(null=True, blank=True)  # 貸出希望日を追加
  return_date = models.DateField(null=True, blank=True)  # 返却予定日を追加
  approval_status = models.CharField(max_length=50, default='承認待ち')
  approval_date = models.DateTimeField(null=True, blank=True)
  approval_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='approved_orders', null=True, blank=True)
  approval_comment = models.TextField(null=True, blank=True)  # コメント用フィールドを追加 # コメントがない場合もあるため、null=True, blank=Trueに設定

  def approve(self, approver):
      """承認処理"""
      self.approval_status = '承認済み'
      self.approval_date = timezone.now()
      self.approval_user = approver
      self.save()
  def reject(self, approver):
      """否決処理"""
      self.approval_status = '否決'
      self.approval_date = timezone.now()
      self.approval_user = approver
      self.save()   

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from equipment.models import Equipment
from django.conf import settings

# カスタム ユーザーマネージャー
class CustomUserManager(BaseUserManager):
    def create_user(self, email, username, password=None, **extra_fields):
        if not email:
            raise ValueError('Email address is required')
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user


# カスタム ユーザーモデル
class CustomUser(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(unique=True, max_length=50, null=False)
    email = models.EmailField(unique=True, null=False)

    is_staff = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    registration_date = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']
    

    objects = CustomUserManager()


    def __str__(self):
        return self.email


#お気に入り機能
class FavoriteEquip(models.Model):
    class Meta:
        unique_together = ('user', 'equip')
        db_table = 'favorite'  # ここでテーブル名を指定

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    equip = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    added_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.equip.name}"

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm #フォームの基本の形をインポート
from django.contrib.auth import get_user_model #ユーザー情報の基本の形をインポート

class CustomUserCreationForm(UserCreationForm):#ユーザーを新規登録するときに使うフォーム
    class Meta(UserCreationForm.Meta):
        model = get_user_model()  # カスタムユーザーモデルを取得
        fields = ('email', 'username','is_staff','is_admin') #フォームを呼び出したときに表示されてほしい項目(modelsで定義している名前を指定)
        labels = {  #フォームを表示したときに、ラベルとして表示されてほしい文字列
         'username':'ユーザー名',
         'email': 'メールアドレス',
         'is_staff': 'スタッフとして登録する',
         'is_admin': '管理者として登録する',
      }
    def clean_username(self):
        username = self.cleaned_data.get('username')
        if get_user_model().objects.filter(username=username).exists():
            raise forms.ValidationError('この ユーザー名 は既に存在します。')  # エラーメッセージをカスタマイズ
        return username
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('この メールアドレス は既に存在します。')  # エラーメッセージをカスタマイズ
        return email
        
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model() # カスタムユーザーモデルを取得
        fields = ('email', 'username', 'is_staff', 'is_admin')
        labels = {
            'username': 'ユーザー名',
            'email': 'メールアドレス',
            'is_staff': 'スタッフとして登録する',
            'is_admin': '管理者として登録する',
        }

    def clean_username(self): #変更するときに、ユーザーネームがエラーかどうかをチェックする
        username = self.cleaned_data.get('username')
        if get_user_model().objects.filter(username=username).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError('このユーザー名は既に使用されています。') # もし既に存在する場合は、ValidationErrorを発生させる
        return username # エラーがなければ、ユーザー名を返す

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if get_user_model().objects.filter(email=email).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError('このメールアドレスは既に使用されています。')
        return email
        

users/views.py
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404,redirect
from django.views import generic
from django.views.generic import ListView,TemplateView,UpdateView #基本機能のビューをインポート
from .forms import CustomUserCreationForm,CustomUserChangeForm      #forms.pyから輸入
from .models import CustomUser,FavoriteEquip #このビュー内でmodels.pyに定義しているCustomUserモデルを使用する
from django.contrib.auth.mixins import LoginRequiredMixin #ログインしていないと見れないようにするためのヤツ
from django.http import HttpResponseForbidden#アクセスを禁止するためのヤツ
from order.models import Order# orderをインポート
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = 'users/index.html' #テンプレートはusers/index.htmlにする

    #ログインしているときは、TOPページを表示させずにメニューへ飛ぶ
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('users:menu')
        return super().dispatch(request, *args, **kwargs)

class SignUpView(generic.CreateView): #新規登録用
    form_class = CustomUserCreationForm #forms.pyで定義しているフォームを使用する
    success_url = reverse_lazy('equipment:list')  # 登録完了後に、書籍一覧(equipment/list.html)にリダイレクトする
    template_name = 'users/sign_up.html' #テンプレートはusers/sign_up.htmlにする

class CustomUserListView(LoginRequiredMixin,ListView): #ユーザー一覧用
    #ユーザーの一覧をみるためのビューの名前をCustomUserListViewにする
    #ビューは、ListViewにする
    #LoginRequiredMixinで、ログインしていないと見れないようにする！
    template_name = 'users/users.html' #テンプレートはusers.htmlにする
    model = CustomUser #使用するモデルはCustomUser(→名前はmodels.pyで定義している)
    context_object_name = 'users' #テンプレートにデータを渡すときの名前をusersとする

    def get_queryset(self):
        return CustomUser.objects.order_by('-registration_date') #データを取得する。そのときに、登録日(registration_date)で並び替える。
    
    #管理者以外にユーザー一覧へのアクセスを許可しない
    def dispatch(self, request, *args, **kwargs):#管理者以外にユーザー一覧へのアクセスを許可しない
    # ログインユーザーのis_adminがTrueかどうかをチェック
        if not request.user.is_admin:
            return HttpResponseForbidden("このページにアクセスする権限がありません。")
        return super().dispatch(request, *args, **kwargs)
    


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = CustomUser
    form_class = CustomUserChangeForm
    template_name = 'users/edit.html'

    def get_object(self, queryset=None):
        user_id = self.kwargs.get("pk")
        return get_object_or_404(CustomUser, pk=user_id)

    def dispatch(self, request, *args, **kwargs):
        user_id = self.kwargs.get("pk")
        user = get_object_or_404(CustomUser, pk=user_id)

        if request.user.is_admin:
            return super().dispatch(request, *args, **kwargs)

        if request.user != user:
            return HttpResponseForbidden("このページにアクセスする権限がありません。")

        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        # 管理者の場合は users:users にリダイレクト
        if self.request.user.is_admin:
            return reverse_lazy('users:users')
        # スタッフの場合は users:mypage にリダイレクト
        elif self.request.user.is_staff:
            return reverse_lazy('users:mypage')
        # デフォルトのリダイレクト先（追加の安全策として）
        return reverse_lazy('users:mypage')
    
    def form_valid(self, form):
        return super().form_valid(form)


    
class MenuView(LoginRequiredMixin, TemplateView):
    template_name = 'users/menu.html' #テンプレートはusers/menu.htmlにする
    

class MyPageView(LoginRequiredMixin, TemplateView):
    template_name = 'users/mypage.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        # ログインしているユーザーの注文情報の最新5件を取得
        context['username'] = user.username
        context['orders'] = Order.objects.filter(user=user).order_by('-order_date')[:5]  # 最新5件に制限
        context['favorites'] = FavoriteEquip.objects.filter(user=user).order_by('-added_at')[:5]  # 最新5件に制限
        return context


class ForgetPasswordView(TemplateView):
    template_name = 'users/forgetpw.html'  # 忘れたパスワード用のテンプレート


class FavoriteListView(LoginRequiredMixin, ListView):
    template_name = 'users/favorite.html'  # 使用するテンプレート
    model = FavoriteEquip  # 使用するモデル
    context_object_name = 'favorites'  # テンプレートに渡すコンテキスト名を変更

    def get_queryset(self):
        # ログインしているユーザーのお気に入りを取得し、追加日で並び替える
        return FavoriteEquip.objects.filter(user=self.request.user).order_by('-added_at')

templates/users/forgetpw.html
{% extends 'base.html' %}
{% load static %}
{% block title %}パスワード再設定{% endblock title %}
{% block content %}

<!--パスワード再設定-->
<div class="title">
    <h2>パスワード再設定</h2>
</div>

<div class="forget-password-container">
    <div class="title-section">
    </div>
    
    <div class="instruction-text">
        <p>ログインIDとご登録メールアドレスを入力し、「送信」を押してください。</p>
        <p>入力されたメールアドレス宛に、パスワード再設定のご案内をさせていただきます。</p>
    </div>
    
    <form action="{% url 'users:forgetpw' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="login_id">ログインID：</label>
            <input type="text" id="login_id" name="login_id" required>
        </div>
        <div class="form-group">
            <label for="email">メールアドレス：</label>
            <input type="email" id="email" name="email" required>
        </div>
        <div class="button-container">
            <input type="submit" value="送信" class="button">
        </div>
    </form>
    
    <div class="back-to-login">
        <a href="{% url 'users:login' %}">▶ ログイン画面に戻る</a>
    </div>
</div>
{% endblock content %}

templates/users/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}トップページ{% endblock title %}
{% block content %}

  <div class="title">
    <h2>書籍貸出管理 -Webシステムへようこそ</h2>
  </div>
  
  <div class="content">
    <p><a href="{% url 'users:login' %}">ログイン</a> または <a href="{% url 'users:register' %}">登録</a> して書籍を管理しましょう。</p>
  </div>

{% endblock content %}

templates/users/menu.html
{% extends "base.html" %}
{% load static %}
{% block title %}メニュー{% endblock title %}
{% block content %}

  <div class="title">
    <h2>メニュー</h2>
  </div>
  
  <div class="content">
    <!--ここからメニュー-->
    <table class="menu-table">
      <tr>
        <td><a href="{% url 'users:mypage' %}">マイページ</a></td>
        <td>ユーザー情報の確認・編集、申請一覧、お気に入り一覧の確認をします。</td>
      </tr>
      <tr>
        <td><a href="{% url 'equipment:list' %}">書籍一覧</a></td>
          <td>備品の一覧・詳細を閲覧します。</td>
      </tr>
      <tr>
        <td><a href="{% url 'order:history' %}">申請一覧</a></td>
          <td>申請の確認・承認(管理者のみ)を行います。</td>
      </tr>
      <tr>
        <td><a href="{% url 'users:favorite' %}">お気に入り一覧</a></td>
          <td>お気に入り一覧の確認をします。</td>
      </tr>
      {% if user.is_admin %}
      <tr>
          <td><a href="{% url 'users:users' %}">ユーザー一覧</a></td>
          <td>(管理者限定)ユーザー情報の確認・編集を行います。</td>
      </tr>
      {% endif %}
  </table>

  </div>

{% endblock content %}

templates/users/mypage.html
{% extends "base.html" %}
{% block title %}マイページ{% endblock title %}  
{% block content %}
<link rel="stylesheet" href="
https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"
/>

<div class="mypage-container">
    {% comment %} <div class="last-login-info">
        <ul>
            <li><strong>最終ログイン:</strong> {{ user.last_login|date:"Y/m/d H:i" }}</li>
        </ul>
    </div> {% endcomment %}
    <h2>{{ user.username }}さんのマイページ</h2>
    <table class="user-info-table">
      <tr>
          <th>ユーザー名</th>
          <td>{{ user.username }}</td>
      </tr>
      <tr>
          <th>メールアドレス</th>
          <td>{{ user.email }}</td>
      </tr>
      <tr>
          <th>ユーザー登録日</th>
          <td>{{ user.registration_date|date:"Y/m/d" }}</td>
      </tr>
<!--      <tr>
          <th>パスワード</th>
          <td>********</td> 
      </tr>--><!-- 伏せ文字で表示 -->
          <tr>
            <th>スタッフ</th>
            <td>
              {% if user.is_staff %}
              <span class="material-symbols-outlined">
                check_circle
              </span>
              {% else %}
              <span class="material-symbols-outlined" style="color:#CCCCCC;">
                check_indeterminate_small
              </span>
              {% endif %}
            </td>
        </tr>
        <tr>
            <th>管理者</th>
            <td>
              {% if user.is_admin %}
              <span class="material-symbols-outlined">
                check_circle
              </span>
              {% else %}
              <span class="material-symbols-outlined" style="color:#CCCCCC;">
                check_indeterminate_small
              </span>
              {% endif %}
            </td>
        </tr>
  </table>
  <div class="button-container">
    <a class="myedit-button" href="{% url 'users:edit' user.id %}">登録情報を編集する</a>
</div>
 <!-- 申請一覧 -->
 <h3>{{ user.username }}さんの申請一覧（最新5件）</h3>
 <a href="{% url 'order:history' %}" class="detail-button" style="float: right; margin-right: 10px;">
  詳細はこちら
</a>
 <table class="mypage-order-history-table" cellspacing="10" cellpadding="10">
     <thead>
         <tr class="order-history-header" align="center">
            <th>書籍名</th>
             <th>貸出希望日</th>
             <th>返却予定日</th>
             <th>承認依頼日</th>
             <th>ステータス</th>
             <th>コメント</th>
         </tr>
     </thead>
     <tbody>
         {% for order in orders %}
         <tr class="order-history-row" align="center">
          <td>
            <div class="tooltip">
              <a href="{% url 'equipment:detail' order.equip.pk %}">{{ order.equip.equip_name }}</a>
              <span class="tooltiptext">
                <center>
                  <img src="{{ order.equip.image.url }}" alt="{{ order.equip.equip_name }}" class="tooltip-image">
                </center>
                <div style="text-align: left; margin-top: 10px; font-size:smaller;">
                貸出状況: {{ order.equip.loan_status }}<br>
                説明　　: {{ order.equip.text }}<br>
                カテゴリ: {{ order.equip.category }}<br>
                状態　　: {{ order.equip.condition }}<br>
                保管場所: {{ order.equip.place }}<br>
                <!--貸出者　: {{ order.user.username}}<br>-->
              </div>
              </span>
            </div>
          </td>
          <td>{{ order.loan_date|date:"Y/m/d" }}</td>
          <td>{{ order.return_date|date:"Y/m/d" }}</td>
          <td>{{ order.order_date|date:"Y/m/d" }}</td>
          <td>
            {% if order.approval_status == '承認待ち' %}
                <span class="status-pending">{{ order.approval_status }}</span>
            {% elif order.approval_status == '承認済み' %}
                <span class="status-approved">{{ order.approval_status }}</span>
            {% elif order.approval_status == '否決' %}
                <span class="status-rejected">{{ order.approval_status }}</span>
            {% else %}
                <span>{{ order.approval_status }}</span>
            {% endif %}
        </td>
          <td>{{ order.approval_comment|default:"-" }}</td> <!-- コメントがない場合は "-" を表示 -->
      </tr>
         {% empty %}
         <tr>
             <td colspan="6">申請がありません</td>
         </tr>
         {% endfor %}
     </tbody>
 </table>
 <!-- お気に入り一覧 -->
 <h3>{{ user.username }}さんのお気に入り一覧（最新5件）</h3>
 <a href="{% url 'users:favorite' %}" class="detail-button" style="float: right; margin-right: 10px;">
  詳細はこちら
  </a>
 <table class="favorite-equip-table" cellspacing="10" cellpadding="10">
     <thead>
         <tr class="favorite-equip-header" align="center">
            <th>書籍名</th>
             <th>カテゴリー</th>
             <th>貸出状況</th>
         </tr>
     </thead>
     <tbody>
         {% for favorite in favorites %}
         <tr class="favorite-equip-row" align="center">
          <td>
            <div class="tooltip">
              <a href="{% url 'equipment:detail' favorite.equip.id %}">{{ favorite.equip.equip_name }}</a>
              <span class="tooltiptext">
                <center>
                  <img src="{{ favorite.equip.image.url }}" alt="{{ favorite.equip.equip_name }}" class="tooltip-image">
                </center>
                <div style="text-align: left; margin-top: 10px; font-size:smaller;">
                貸出状況: {{ favorite.equip.loan_status }}<br>
                説明　　: {{ favorite.equip.text }}<br>
                カテゴリ: {{ favorite.equip.category }}<br>
                状態　　: {{ favorite.equip.condition }}<br>
                保管場所: {{ favorite.equip.place }}<br>
                <!--貸出者　: {{ order.user.username}}<br>-->
                </div>
              </span>
            </div>
          </td>

             <td>{{ favorite.equip.category }}</td>

             <td><!-- 貸出状況を表示 -->
              {% if favorite.equip.loan_status == '貸出可' %}
              <span class="material-symbols-outlined">
                  <font color="#69c44b"><b>circle</span>
              </span>
                貸出可
              {% elif favorite.equip.loan_status == '貸出不可' %}
                <span class="material-symbols-outlined">
                  <font color="#EB6161"><b>close
                </span>
                貸出不可
                  </font></b>
              {% elif favorite.equip.loan_status == '貸出中' %}
              <span class="material-symbols-outlined">
                <font color="#EB6161"><b>do_not_disturb_on
              </span>
              貸出中
                </font></b>
              {% else %}
              <span class="material-symbols-outlined">
                <font color="#00A0A8"><b>question_mark
              </span>
              その他
              </font></b>
              {% endif %}
             </td> 

         </tr>
         {% empty %}
         <tr>
             <td colspan="3">お気に入りがありません</td>
         </tr>
         {% endfor %}
     </tbody>
 </table>
</div>


<script>
  document.addEventListener("DOMContentLoaded", function() {
    const images = document.querySelectorAll("img.tooltip-image");
    images.forEach(imgElement => {
      imgElement.onerror = function() {
        // 画像が破損している場合、画像を非表示にし、no-imageクラスを表示
        imgElement.style.display = "none";
        const noImageDiv = document.createElement("div");
        noImageDiv.className = "tooltip-noimage";
        noImageDiv.innerHTML = `
          <span class="material-symbols-outlined">
            <font color="#FFFFFF" size="20">
              no_photography
            </font>
          </span>
        `;
        imgElement.parentNode.appendChild(noImageDiv);
      }
    });
  });
</script>

{% endblock content %}

templates/users/sign_in.html
{% extends "base.html" %}
{% load static %}
{% block title %}ログイン{% endblock title %}
{% block content %}

<!--ログインページ-->
<div class="title">
    <h2>ログイン</h2>
</div>

<form method="post">
    {% csrf_token %}
    {% if form.errors %}
    <div class="field-error">
        <p>ユーザIDまたは、パスワードが違います</p>
    </div>
{% endif %}

    <div class="field">
        <label for="{{ form.username.id_for_label }}">ユーザー名：</label>
        {{ form.username }}
        {% if form.username.errors %}
        <ul class="errorlist">
            {% for error in form.username.errors %}
            <li><font color="#E6371E">{{ error }}</font></li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>

    <div class="field">
        <label for="{{ form.password.id_for_label }}">{{ form.password.label }}：</label>
        {{ form.password }}
        {% if form.password.errors %}
        <ul class="errorlist">
            {% for error in form.password.errors %}
            <li><font color="#E6371E">{{ error }}</font></li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>

    <div class="button-container">
        <input type="submit" value="ログイン" class="button">
    </div>
</form>

<p>アカウントをお持ちでないですか？</p>
<br>
<div class="back-to-login">
	<p><a href="{% url 'users:register' %}">▶ 登録はこちら</a></p>
	<br>
	<p><a href="{% url 'users:forgetpw' %}">▶ パスワードを忘れた方はこちら</a></p>
	<br>
</div>

{% endblock content %}

templates/users/sign_up.html
{% extends "base.html" %}
{% load static %}
{% block title %}トップページ{% endblock title %}
{% block content %}
<!--新規登録ページ-->
<div class="title">
    <h2>ユーザー新規登録</h2>
</div>
<form method="post">
    {% csrf_token %}
    {% if form.errors %}
        <div class="field-error">
            <p>入力にエラーがあります。もう一度ご確認ください。</p>
        </div>
    {% endif %}
    <div class="field">
        {% if form.username.errors %}
        <ul class="errorlist">
            {% for error in form.username.errors %}
            <li><font color="#E6371E">{{ error }}</font></li>
            {% endfor %}
        </ul>
            {% endif %}
    </div>
    <div class="field">
        {{ form.username.label_tag }}
        {{ form.username }}
    </div>
    <div class="field">
        {% if form.email.errors %}
        <ul class="errorlist">
        {% for error in form.email.errors %}
            <li><font color="#E6371E">{{ error }}</font></li>
            {% endfor %}
        </ul>
        {% endif %}
        {{ form.email.label_tag }}
        {{ form.email }}
    </div>
    <div class="field">
        {% if form.password1.errors %}
        <ul class="errorlist">
            {% for error in form.password1.errors %}
            <li><font color="#E6371E">{{ error }}</font></li>
            {% endfor %}
        </ul>
        {% endif %}
        {{ form.password1.label_tag }}<span>(英数字含む8文字以上)</span>
        {{ form.password1 }}
    </div>
    <div class="field">
        {% if form.password2.errors %}
        <ul class="errorlist">
            {% for error in form.password2.errors %}
            <li><font color="#E6371E">{{ error }}</font></li>
            {% endfor %}
        </ul>
        {% endif %}
        {{ form.password2.label_tag }}
        {{ form.password2 }}
    </div>
    <div class="field-info">
        <p>
            ユーザー名は、半角アルファベット、半角数字、@/./+/-/_ で150文字以下にしてください。<br><br>
            あなたの他の個人情報と似ているパスワードにはできません。<br>
            パスワードは最低 8 文字以上必要です。<br>
            よく使われるパスワードにはできません。<br>
            数字だけのパスワードにはできません。
        </p>
    </div>
    <center>
    <div class="fieldstaff">
        {{ form.is_staff.label_tag }}
        {{ form.is_staff }}
    </div>
    <div class="fieldstaff">
        {{ form.is_admin.label_tag }}
        {{ form.is_admin }}
    </div>
    </center>
    <div class="button-container">
        <input type="submit" value="登録" class="button">
    </div>
    <div class="back-to-login">
        <a href="{% url 'users:login' %}">▶ ログイン画面に戻る</a>
    </div>
</form>
{% endblock content %}